<?php
/**
 * @file
 * Module file for dfp.
 */

/**
 * @defgroup Carrusel: Block
 * @ingroup nnmx
 * @{
 * create a custom slideshow.
 */


/**
 * Implements hook_theme().
 */
function reproductor_theme($existing, $type, $theme, $path) {
  return array(
    'reproductor' => array(
      'variables' => array('videos' => NULL),
      ),
    'reproductor_item' => array(
      'variables' => array('nid' => NULL),
      ),
  );
}

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function reproductor_block_info() {
  $blocks['reproductor_nnmx'] = array(
    'info' => 'Reproductor nnmx',
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function reproductor_block_view($delta = '') {

  switch($delta) {
    case 'reproductor_nnmx':
      $block['subject'] = '';
      $block['content'] = theme('reproductor', array('videos' => _reproductor_get_all_data()));
    break;
  }
  return $block;
}


/**
* them carrusel
*/
function theme_reproductor($variables) {
  $temp_node = node_load($variables['videos'][0]);
  /*echo '<pre>';
  print_r($temp_node);
  echo '</pre>';*/
  $output = '';
  $output .= '<section class="secciones reproductor clearfix">';
  $output .= '<div class="view-header"><h1>TV Noticias</h1></div>';
  $output .= '<div class="rep-lista">';
  $output .= '<ul>';
  foreach($variables['videos'] as $nid) {
   $output .= theme('reproductor_item', array('nid' => $nid));
  }
  $output .= '</ul>';
  $output .= '</div>';
  $output .= '<article class="rep-play">';
  $output .= '<iframe width="130" height="73" src="//www.youtube.com/embed/' . $temp_node->field_youtube['und'][0]['video_id'] . '?rel=0" frameborder="0" allowfullscreen></iframe>';
  $output .= '<h1>' . $temp_node->title . '</h1>';
  $output .= '<p>' . $temp_node->body['und'][0]['safe_summary'] . '</p>';
  $output .= '</article>';
  $output .= '</section>';
return $output;
}

/**
* them carrusel
*/
function theme_reproductor_item($variables) {
  $temp_node = node_load($variables['nid']);
  $output = '';
  $output .= '<li class="rep-item">';
  $output .= '<img src="http://img.youtube.com/vi/' . $temp_node->field_youtube['und'][0]['video_id'] . '/3.jpg" />';
  $output .= '<div class="rep-item-datos">';
  $output .= '<h3>' . $temp_node->title . '</h3>';
  $output .= '<p>' . $temp_node->body['und'][0]['safe_summary'] . '</p>';
  $output .= '</div>';
  $output .= '</li>';
return $output;
}


/**
* retrieve an array with 15 node id's filtered by path
*/
function _reproductor_get_all_data() {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
  ->entityCondition('bundle', array('video'))
  ->propertyCondition('status', 1);
  $query->propertyOrderBy('created', 'DESC');
  $query->range(0, 15);
  $query->addMetaData('account', user_load(1));
  $result = $query->execute();
  return array_keys($result['node']);
}

/**
 * @} End of "defgroup carrusel".
 */
